# Generated by Django 2.1.4 on 2019-01-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='porforlio_site',
            new_name='portfolio_site',
        ),
    ]
